#!/bin/sh

if [ "$(git rev-parse --abbrev-ref HEAD | grep '^wip')" ]; then
    echo "\033[0;31m[ABORT] You cannot push a branch whose prefix is \`wip\`.\033[0;39m" 1>&2
    exit 1
fi

if [ "$(git log --oneline master..head | grep 'fixup! ')" ]; then
    echo "\033[0;31m[ABORT] You cannot push a commit whose title starts \`fixup! \`.\033[0;39m" 1>&2
    exit 1
fi

exit 0
